In [1]:
#데이터 핸들링, 기타
import numpy as np
import pandas as pd
import re
import math
import time
from datetime import datetime #JSON 날짜 변환

#시각화
import matplotlib.pylab as plt
import matplotlib.font_manager as fm
import seaborn as sns

#크롤링 및 JSON 핸들링
from urllib.request import urlopen
from pandas.io.json import json_normalize
import requests
import bs4
import json

In [3]:
import requests
import json

In [4]:
url = "http://www.wiseindex.com/DataCenter/GridData?currentPage=1&endDT=2019-11-06&fromDT=2000-01-01&index_ids=WGI0002T&isEnd=1&itemType=3&perPage=100&term=4"

In [65]:
rqt = urlopen(url) #request
datat = json.loads(rqt.read().decode()) #JSON 파싱 후
df1 = json_normalize(datat) #1페이지 -> to_dataframe

In [66]:
df1

,IDX1_VAL1,IDX1_VAL10,IDX1_VAL2,IDX1_VAL3,IDX1_VAL4,IDX1_VAL5,IDX1_VAL6,IDX1_VAL7,IDX1_VAL8,IDX1_VAL9,ROW_IDX,TOT_ROW,TRD_DT
0,5373.97,2.05,140875.01,220419.45,15.40,0.60,0.38,8.05,6.13,16.56,1,38,/Date(1569769200000)/
1,4665.74,2.03,136580.81,212584.34,16.50,0.62,0.38,8.34,5.12,-6.01,2,38,/Date(1561647600000)/
2,5214.58,2.20,137447.43,209505.05,13.89,0.54,0.35,7.65,1.01,-34.26,3,38,/Date(1553785200000)/
3,5214.58,2.26,137447.43,209505.05,13.51,0.53,0.34,7.61,1.01,-34.26,4,38,/Date(1545922800000)/
4,5444.26,2.01,137351.29,208695.41,14.53,0.59,0.38,8.16,4.15,-13.95,5,38,/Date(1538060400000)/
5,6848.96,2.15,135859.22,209162.56,13.42,0.56,0.36,7.67,-3.60,-38.17,6,38,/Date(1530198000000)/
6,8013.05,2.14,136359.36,211124.64,9.98,0.60,0.38,6.92,7.97,-31.33,7,38,/Date(1522335600000)/
7,8013.05,2.01,136359.36,211124.64,10.67,0.64,0.41,7.23,7.97,-31.33,8,38,/Date(1514386800000)/
8,9339.86,2.11,134923.97,207203.40,8.75,0.62,0.39,6.36,-4.03,-28.68,9,38,/Date(1506610800000)/
9,11119.13,1.93,132289.19,207643.28,8.28,0.70,0.43,6.08,0.78,-13.44,10,38,/Date(1498748400000)/
10,11781.20,1.98,127370.78,207221.78,7.38,0.70,0.42,5.64,-3.36,-15.08,11,38,/Date(1490886000000)/
11,11781.20,1.98,127370.78,207221.78,7.34,0.70,0.42,5.62,-3.36,-15.08,12,38,/Date(1482937200000)/
12,11386.23,1.97,126239.00,208935.86,7.67,0.71,0.42,5.97,8.72,6.42,13,38,/Date(1475161200000)/
13,11522.82,2.05,121748.73,204423.79,7.33,0.70,0.41,6.01,6.86,-16.16,14,38,/Date(1467212400000)/
14,11762.47,1.53,120526.57,201661.75,7.79,0.78,0.46,6.23,8.64,-1.09,15,38,/Date(1459350000000)/
15,11762.47,1.55,120526.57,201661.75,7.69,0.77,0.45,6.17,8.64,-1.09,16,38,/Date(1451401200000)/
16,12297.27,1.48,116633.86,197890.07,7.65,0.82,0.49,5.92,-0.01,-11.21,17,38,/Date(1443538800000)/
17,13437.74,1.64,111528.82,196771.32,6.35,0.77,0.43,5.11,10.79,7.47,18,38,/Date(1435590000000)/
18,15424.97,0.99,109223.91,191006.91,6.30,0.91,0.51,5.08,2.52,-9.13,19,38,/Date(1427727600000)/
19,15424.97,0.95,109223.91,191006.91,6.55,0.94,0.53,5.24,2.52,-9.13,20,38,/Date(1419865200000)/
20,17621.31,0.86,112825.84,199915.97,6.71,1.07,0.59,5.41,0.53,-8.23,21,38,/Date(1412002800000)/
21,17131.79,0.80,106564.65,199387.32,7.31,1.20,0.64,5.88,1.75,13.96,22,38,/Date(1404054000000)/
22,15577.18,0.74,98934.36,198535.59,8.40,1.34,0.67,6.30,3.81,0.93,23,38,/Date(1396191600000)/
23,15577.18,0.77,98934.36,198535.59,8.07,1.29,0.65,6.10,3.81,0.93,24,38,/Date(1388329200000)/
24,15250.86,0.74,95489.02,192766.73,8.48,1.38,0.67,6.32,4.89,-5.37,25,38,/Date(1380466800000)/
25,16172.96,0.81,87911.77,187372.62,7.73,1.32,0.62,5.93,0.73,-17.74,26,38,/Date(1372345200000)/
26,16110.80,0.74,85771.17,187235.15,7.43,1.42,0.64,5.65,8.40,-3.37,27,38,/Date(1364482800000)/
27,16110.80,0.74,85771.17,187235.15,7.42,1.41,0.64,5.65,8.40,-3.37,28,38,/Date(1356620400000)/
28,15294.33,0.66,81746.03,183924.24,8.75,1.66,0.73,6.56,9.85,12.63,29,38,/Date(1348758000000)/
29,14453.93,0.69,74232.56,174916.42,8.31,1.65,0.70,6.33,33.72,32.13,30,38,/Date(1340895600000)/
30,13809.86,0.58,71863.04,415111.45,9.38,1.83,1.00,19.03,28.21,48.87,31,38,/Date(1333033200000)/
31,13809.86,0.62,71863.04,415111.45,8.76,1.71,0.94,17.94,28.21,48.87,32,38,/Date(1325084400000)/
32,13647.70,0.60,69150.10,390218.09,9.23,1.84,0.92,15.52,21.01,32.41,33,38,/Date(1317308400000)/
33,11601.11,0.53,59648.70,97734.41,11.80,2.26,0.99,15.99,16.08,26.35,34,38,/Date(1309359600000)/
34,10886.33,0.42,56350.58,94208.29,12.12,2.37,1.36,8.12,20.26,28.31,35,38,/Date(1301497200000)/
35,10886.33,0.51,56350.58,94208.29,10.15,1.99,1.17,6.80,20.26,28.31,36,38,/Date(1293634800000)/
36,10362.86,0.58,53135.29,90542.54,9.33,1.84,1.07,6.19,28.15,43.59,37,38,/Date(1285772400000)/
37,7844.26,0.67,48263.55,81094.15,8.96,1.72,0.99,5.98,11.38,66.37,38,38,/Date(1277823600000)/

In [67]:
len(datat)

38

In [68]:
d = df1['TRD_DT'][0]

In [69]:
d

'/Date(1569769200000)/'

In [71]:
d = df1['TRD_DT'].iloc[0][6:-2]
d = int(d[:10])

In [73]:
datetime.fromtimestamp(d).strftime('%Y-%m-%d %I:%M:%S %p')

'2019-09-30 12:00:00 AM'

In [74]:
for i in range(0, len(df1)):

    d = df1['TRD_DT'].iloc[i][6:-2]
    d = int(d[:10])
    d = datetime.fromtimestamp(d).strftime('%Y-%m-%d %I:%M:%S %p')
    df1['TRD_DT'].iloc[i] = d

C:\Users\ASUS\Anaconda3\lib\site-packages\pandas\core\indexing.py:190: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._setitem_with_indexer(indexer, value)

In [75]:
title = {"IDX1_VAL1": "EPS (Earnings per share)",
"IDX1_VAL2": "BPS (Book Value)",
"IDX1_VAL3": "SPS (Sales)",
"IDX1_VAL4": "PER(Price-Earnings Ratio)",
"IDX1_VAL5": "PBR",
"IDX1_VAL6": "PSR",
"IDX1_VAL7": "EV/EVITDA",
"IDX1_VAL8": "매출액 Growth",
"IDX1_VAL9": "영업이익 Growth",
"IDX1_VAL10": "배당수익률(FY0)"}

In [78]:
# inplace를 하는 이유는 rename하는 내용이 df1에 바로 적용되서 저장되게 하는 인자.
df1.rename(columns=title, inplace=True)

In [79]:
df1

,EPS (Earnings per share),배당수익률(FY0),BPS (Book Value),SPS (Sales),PER(Price-Earnings Ratio),PBR,PSR,EV/EVITDA,매출액 Growth,영업이익 Growth,ROW_IDX,TOT_ROW,TRD_DT
0,5373.97,2.05,140875.01,220419.45,15.40,0.60,0.38,8.05,6.13,16.56,1,38,2019-09-30 12:00:00 AM
1,4665.74,2.03,136580.81,212584.34,16.50,0.62,0.38,8.34,5.12,-6.01,2,38,2019-06-28 12:00:00 AM
2,5214.58,2.20,137447.43,209505.05,13.89,0.54,0.35,7.65,1.01,-34.26,3,38,2019-03-29 12:00:00 AM
3,5214.58,2.26,137447.43,209505.05,13.51,0.53,0.34,7.61,1.01,-34.26,4,38,2018-12-28 12:00:00 AM
4,5444.26,2.01,137351.29,208695.41,14.53,0.59,0.38,8.16,4.15,-13.95,5,38,2018-09-28 12:00:00 AM
5,6848.96,2.15,135859.22,209162.56,13.42,0.56,0.36,7.67,-3.60,-38.17,6,38,2018-06-29 12:00:00 AM
6,8013.05,2.14,136359.36,211124.64,9.98,0.60,0.38,6.92,7.97,-31.33,7,38,2018-03-30 12:00:00 AM
7,8013.05,2.01,136359.36,211124.64,10.67,0.64,0.41,7.23,7.97,-31.33,8,38,2017-12-28 12:00:00 AM
8,9339.86,2.11,134923.97,207203.40,8.75,0.62,0.39,6.36,-4.03,-28.68,9,38,2017-09-29 12:00:00 AM
9,11119.13,1.93,132289.19,207643.28,8.28,0.70,0.43,6.08,0.78,-13.44,10,38,2017-06-30 12:00:00 AM
10,11781.20,1.98,127370.78,207221.78,7.38,0.70,0.42,5.64,-3.36,-15.08,11,38,2017-03-31 12:00:00 AM
11,11781.20,1.98,127370.78,207221.78,7.34,0.70,0.42,5.62,-3.36,-15.08,12,38,2016-12-29 12:00:00 AM
12,11386.23,1.97,126239.00,208935.86,7.67,0.71,0.42,5.97,8.72,6.42,13,38,2016-09-30 12:00:00 AM
13,11522.82,2.05,121748.73,204423.79,7.33,0.70,0.41,6.01,6.86,-16.16,14,38,2016-06-30 12:00:00 AM
14,11762.47,1.53,120526.57,201661.75,7.79,0.78,0.46,6.23,8.64,-1.09,15,38,2016-03-31 12:00:00 AM
15,11762.47,1.55,120526.57,201661.75,7.69,0.77,0.45,6.17,8.64,-1.09,16,38,2015-12-30 12:00:00 AM
16,12297.27,1.48,116633.86,197890.07,7.65,0.82,0.49,5.92,-0.01,-11.21,17,38,2015-09-30 12:00:00 AM
17,13437.74,1.64,111528.82,196771.32,6.35,0.77,0.43,5.11,10.79,7.47,18,38,2015-06-30 12:00:00 AM
18,15424.97,0.99,109223.91,191006.91,6.30,0.91,0.51,5.08,2.52,-9.13,19,38,2015-03-31 12:00:00 AM
19,15424.97,0.95,109223.91,191006.91,6.55,0.94,0.53,5.24,2.52,-9.13,20,38,2014-12-30 12:00:00 AM
20,17621.31,0.86,112825.84,199915.97,6.71,1.07,0.59,5.41,0.53,-8.23,21,38,2014-09-30 12:00:00 AM
21,17131.79,0.80,106564.65,199387.32,7.31,1.20,0.64,5.88,1.75,13.96,22,38,2014-06-30 12:00:00 AM
22,15577.18,0.74,98934.36,198535.59,8.40,1.34,0.67,6.30,3.81,0.93,23,38,2014-03-31 12:00:00 AM
23,15577.18,0.77,98934.36,198535.59,8.07,1.29,0.65,6.10,3.81,0.93,24,38,2013-12-30 12:00:00 AM
24,15250.86,0.74,95489.02,192766.73,8.48,1.38,0.67,6.32,4.89,-5.37,25,38,2013-09-30 12:00:00 AM
25,16172.96,0.81,87911.77,187372.62,7.73,1.32,0.62,5.93,0.73,-17.74,26,38,2013-06-28 12:00:00 AM
26,16110.80,0.74,85771.17,187235.15,7.43,1.42,0.64,5.65,8.40,-3.37,27,38,2013-03-29 12:00:00 AM
27,16110.80,0.74,85771.17,187235.15,7.42,1.41,0.64,5.65,8.40,-3.37,28,38,2012-12-28 12:00:00 AM
28,15294.33,0.66,81746.03,183924.24,8.75,1.66,0.73,6.56,9.85,12.63,29,38,2012-09-28 12:00:00 AM
29,14453.93,0.69,74232.56,174916.42,8.31,1.65,0.70,6.33,33.72,32.13,30,38,2012-06-29 12:00:00 AM
30,13809.86,0.58,71863.04,415111.45,9.38,1.83,1.00,19.03,28.21,48.87,31,38,2012-03-30 12:00:00 AM
31,13809.86,0.62,71863.04,415111.45,8.76,1.71,0.94,17.94,28.21,48.87,32,38,2011-12-29 12:00:00 AM
32,13647.70,0.60,69150.10,390218.09,9.23,1.84,0.92,15.52,21.01,32.41,33,38,2011-09-30 12:00:00 AM
33,11601.11,0.53,59648.70,97734.41,11.80,2.26,0.99,15.99,16.08,26.35,34,38,2011-06-30 12:00:00 AM
34,10886.33,0.42,56350.58,94208.29,12.12,2.37,1.36,8.12,20.26,28.31,35,38,2011-03-31 12:00:00 AM
35,10886.33,0.51,56350.58,94208.29,10.15,1.99,1.17,6.80,20.26,28.31,36,38,2010-12-30 12:00:00 AM
36,10362.86,0.58,53135.29,90542.54,9.33,1.84,1.07,6.19,28.15,43.59,37,38,2010-09-30 12:00:00 AM
37,7844.26,0.67,48263.55,81094.15,8.96,1.72,0.99,5.98,11.38,66.37,38,38,2010-06-30 12:00:00 AM

In [80]:
del df1['ROW_IDX']

In [81]:
del df1['TOT_ROW']

In [82]:
df1.rename(columns={'TRD_DT':"Date"}, inplace=True)

In [90]:
list(df1.columns)

['EPS (Earnings per share)',
 '배당수익률(FY0)',
 'BPS (Book Value)',
 'SPS (Sales)',
 'PER(Price-Earnings Ratio)',
 'PBR',
 'PSR',
 'EV/EVITDA',
 '매출액 Growth',
 '영업이익 Growth',
 'Date']

In [85]:
a = list(df1.columns)[:-1]

In [86]:
a

['EPS (Earnings per share)',
 '배당수익률(FY0)',
 'BPS (Book Value)',
 'SPS (Sales)',
 'PER(Price-Earnings Ratio)',
 'PBR',
 'PSR',
 'EV/EVITDA',
 '매출액 Growth',
 '영업이익 Growth']

In [88]:
a.insert(0, 'Date')

In [91]:
a

['Date',
 'EPS (Earnings per share)',
 '배당수익률(FY0)',
 'BPS (Book Value)',
 'SPS (Sales)',
 'PER(Price-Earnings Ratio)',
 'PBR',
 'PSR',
 'EV/EVITDA',
 '매출액 Growth',
 '영업이익 Growth']

In [92]:
df1

,EPS (Earnings per share),배당수익률(FY0),BPS (Book Value),SPS (Sales),PER(Price-Earnings Ratio),PBR,PSR,EV/EVITDA,매출액 Growth,영업이익 Growth,Date
0,5373.97,2.05,140875.01,220419.45,15.40,0.60,0.38,8.05,6.13,16.56,2019-09-30 12:00:00 AM
1,4665.74,2.03,136580.81,212584.34,16.50,0.62,0.38,8.34,5.12,-6.01,2019-06-28 12:00:00 AM
2,5214.58,2.20,137447.43,209505.05,13.89,0.54,0.35,7.65,1.01,-34.26,2019-03-29 12:00:00 AM
3,5214.58,2.26,137447.43,209505.05,13.51,0.53,0.34,7.61,1.01,-34.26,2018-12-28 12:00:00 AM
4,5444.26,2.01,137351.29,208695.41,14.53,0.59,0.38,8.16,4.15,-13.95,2018-09-28 12:00:00 AM
5,6848.96,2.15,135859.22,209162.56,13.42,0.56,0.36,7.67,-3.60,-38.17,2018-06-29 12:00:00 AM
6,8013.05,2.14,136359.36,211124.64,9.98,0.60,0.38,6.92,7.97,-31.33,2018-03-30 12:00:00 AM
7,8013.05,2.01,136359.36,211124.64,10.67,0.64,0.41,7.23,7.97,-31.33,2017-12-28 12:00:00 AM
8,9339.86,2.11,134923.97,207203.40,8.75,0.62,0.39,6.36,-4.03,-28.68,2017-09-29 12:00:00 AM
9,11119.13,1.93,132289.19,207643.28,8.28,0.70,0.43,6.08,0.78,-13.44,2017-06-30 12:00:00 AM
10,11781.20,1.98,127370.78,207221.78,7.38,0.70,0.42,5.64,-3.36,-15.08,2017-03-31 12:00:00 AM
11,11781.20,1.98,127370.78,207221.78,7.34,0.70,0.42,5.62,-3.36,-15.08,2016-12-29 12:00:00 AM
12,11386.23,1.97,126239.00,208935.86,7.67,0.71,0.42,5.97,8.72,6.42,2016-09-30 12:00:00 AM
13,11522.82,2.05,121748.73,204423.79,7.33,0.70,0.41,6.01,6.86,-16.16,2016-06-30 12:00:00 AM
14,11762.47,1.53,120526.57,201661.75,7.79,0.78,0.46,6.23,8.64,-1.09,2016-03-31 12:00:00 AM
15,11762.47,1.55,120526.57,201661.75,7.69,0.77,0.45,6.17,8.64,-1.09,2015-12-30 12:00:00 AM
16,12297.27,1.48,116633.86,197890.07,7.65,0.82,0.49,5.92,-0.01,-11.21,2015-09-30 12:00:00 AM
17,13437.74,1.64,111528.82,196771.32,6.35,0.77,0.43,5.11,10.79,7.47,2015-06-30 12:00:00 AM
18,15424.97,0.99,109223.91,191006.91,6.30,0.91,0.51,5.08,2.52,-9.13,2015-03-31 12:00:00 AM
19,15424.97,0.95,109223.91,191006.91,6.55,0.94,0.53,5.24,2.52,-9.13,2014-12-30 12:00:00 AM
20,17621.31,0.86,112825.84,199915.97,6.71,1.07,0.59,5.41,0.53,-8.23,2014-09-30 12:00:00 AM
21,17131.79,0.80,106564.65,199387.32,7.31,1.20,0.64,5.88,1.75,13.96,2014-06-30 12:00:00 AM
22,15577.18,0.74,98934.36,198535.59,8.40,1.34,0.67,6.30,3.81,0.93,2014-03-31 12:00:00 AM
23,15577.18,0.77,98934.36,198535.59,8.07,1.29,0.65,6.10,3.81,0.93,2013-12-30 12:00:00 AM
24,15250.86,0.74,95489.02,192766.73,8.48,1.38,0.67,6.32,4.89,-5.37,2013-09-30 12:00:00 AM
25,16172.96,0.81,87911.77,187372.62,7.73,1.32,0.62,5.93,0.73,-17.74,2013-06-28 12:00:00 AM
26,16110.80,0.74,85771.17,187235.15,7.43,1.42,0.64,5.65,8.40,-3.37,2013-03-29 12:00:00 AM
27,16110.80,0.74,85771.17,187235.15,7.42,1.41,0.64,5.65,8.40,-3.37,2012-12-28 12:00:00 AM
28,15294.33,0.66,81746.03,183924.24,8.75,1.66,0.73,6.56,9.85,12.63,2012-09-28 12:00:00 AM
29,14453.93,0.69,74232.56,174916.42,8.31,1.65,0.70,6.33,33.72,32.13,2012-06-29 12:00:00 AM
30,13809.86,0.58,71863.04,415111.45,9.38,1.83,1.00,19.03,28.21,48.87,2012-03-30 12:00:00 AM
31,13809.86,0.62,71863.04,415111.45,8.76,1.71,0.94,17.94,28.21,48.87,2011-12-29 12:00:00 AM
32,13647.70,0.60,69150.10,390218.09,9.23,1.84,0.92,15.52,21.01,32.41,2011-09-30 12:00:00 AM
33,11601.11,0.53,59648.70,97734.41,11.80,2.26,0.99,15.99,16.08,26.35,2011-06-30 12:00:00 AM
34,10886.33,0.42,56350.58,94208.29,12.12,2.37,1.36,8.12,20.26,28.31,2011-03-31 12:00:00 AM
35,10886.33,0.51,56350.58,94208.29,10.15,1.99,1.17,6.80,20.26,28.31,2010-12-30 12:00:00 AM
36,10362.86,0.58,53135.29,90542.54,9.33,1.84,1.07,6.19,28.15,43.59,2010-09-30 12:00:00 AM
37,7844.26,0.67,48263.55,81094.15,8.96,1.72,0.99,5.98,11.38,66.37,2010-06-30 12:00:00 AM

In [93]:
df1 = df1[a]

In [94]:
df1

,Date,EPS (Earnings per share),배당수익률(FY0),BPS (Book Value),SPS (Sales),PER(Price-Earnings Ratio),PBR,PSR,EV/EVITDA,매출액 Growth,영업이익 Growth
0,2019-09-30 12:00:00 AM,5373.97,2.05,140875.01,220419.45,15.40,0.60,0.38,8.05,6.13,16.56
1,2019-06-28 12:00:00 AM,4665.74,2.03,136580.81,212584.34,16.50,0.62,0.38,8.34,5.12,-6.01
2,2019-03-29 12:00:00 AM,5214.58,2.20,137447.43,209505.05,13.89,0.54,0.35,7.65,1.01,-34.26
3,2018-12-28 12:00:00 AM,5214.58,2.26,137447.43,209505.05,13.51,0.53,0.34,7.61,1.01,-34.26
4,2018-09-28 12:00:00 AM,5444.26,2.01,137351.29,208695.41,14.53,0.59,0.38,8.16,4.15,-13.95
5,2018-06-29 12:00:00 AM,6848.96,2.15,135859.22,209162.56,13.42,0.56,0.36,7.67,-3.60,-38.17
6,2018-03-30 12:00:00 AM,8013.05,2.14,136359.36,211124.64,9.98,0.60,0.38,6.92,7.97,-31.33
7,2017-12-28 12:00:00 AM,8013.05,2.01,136359.36,211124.64,10.67,0.64,0.41,7.23,7.97,-31.33
8,2017-09-29 12:00:00 AM,9339.86,2.11,134923.97,207203.40,8.75,0.62,0.39,6.36,-4.03,-28.68
9,2017-06-30 12:00:00 AM,11119.13,1.93,132289.19,207643.28,8.28,0.70,0.43,6.08,0.78,-13.44
10,2017-03-31 12:00:00 AM,11781.20,1.98,127370.78,207221.78,7.38,0.70,0.42,5.64,-3.36,-15.08
11,2016-12-29 12:00:00 AM,11781.20,1.98,127370.78,207221.78,7.34,0.70,0.42,5.62,-3.36,-15.08
12,2016-09-30 12:00:00 AM,11386.23,1.97,126239.00,208935.86,7.67,0.71,0.42,5.97,8.72,6.42
13,2016-06-30 12:00:00 AM,11522.82,2.05,121748.73,204423.79,7.33,0.70,0.41,6.01,6.86,-16.16
14,2016-03-31 12:00:00 AM,11762.47,1.53,120526.57,201661.75,7.79,0.78,0.46,6.23,8.64,-1.09
15,2015-12-30 12:00:00 AM,11762.47,1.55,120526.57,201661.75,7.69,0.77,0.45,6.17,8.64,-1.09
16,2015-09-30 12:00:00 AM,12297.27,1.48,116633.86,197890.07,7.65,0.82,0.49,5.92,-0.01,-11.21
17,2015-06-30 12:00:00 AM,13437.74,1.64,111528.82,196771.32,6.35,0.77,0.43,5.11,10.79,7.47
18,2015-03-31 12:00:00 AM,15424.97,0.99,109223.91,191006.91,6.30,0.91,0.51,5.08,2.52,-9.13
19,2014-12-30 12:00:00 AM,15424.97,0.95,109223.91,191006.91,6.55,0.94,0.53,5.24,2.52,-9.13
20,2014-09-30 12:00:00 AM,17621.31,0.86,112825.84,199915.97,6.71,1.07,0.59,5.41,0.53,-8.23
21,2014-06-30 12:00:00 AM,17131.79,0.80,106564.65,199387.32,7.31,1.20,0.64,5.88,1.75,13.96
22,2014-03-31 12:00:00 AM,15577.18,0.74,98934.36,198535.59,8.40,1.34,0.67,6.30,3.81,0.93
23,2013-12-30 12:00:00 AM,15577.18,0.77,98934.36,198535.59,8.07,1.29,0.65,6.10,3.81,0.93
24,2013-09-30 12:00:00 AM,15250.86,0.74,95489.02,192766.73,8.48,1.38,0.67,6.32,4.89,-5.37
25,2013-06-28 12:00:00 AM,16172.96,0.81,87911.77,187372.62,7.73,1.32,0.62,5.93,0.73,-17.74
26,2013-03-29 12:00:00 AM,16110.80,0.74,85771.17,187235.15,7.43,1.42,0.64,5.65,8.40,-3.37
27,2012-12-28 12:00:00 AM,16110.80,0.74,85771.17,187235.15,7.42,1.41,0.64,5.65,8.40,-3.37
28,2012-09-28 12:00:00 AM,15294.33,0.66,81746.03,183924.24,8.75,1.66,0.73,6.56,9.85,12.63
29,2012-06-29 12:00:00 AM,14453.93,0.69,74232.56,174916.42,8.31,1.65,0.70,6.33,33.72,32.13
30,2012-03-30 12:00:00 AM,13809.86,0.58,71863.04,415111.45,9.38,1.83,1.00,19.03,28.21,48.87
31,2011-12-29 12:00:00 AM,13809.86,0.62,71863.04,415111.45,8.76,1.71,0.94,17.94,28.21,48.87
32,2011-09-30 12:00:00 AM,13647.70,0.60,69150.10,390218.09,9.23,1.84,0.92,15.52,21.01,32.41
33,2011-06-30 12:00:00 AM,11601.11,0.53,59648.70,97734.41,11.80,2.26,0.99,15.99,16.08,26.35
34,2011-03-31 12:00:00 AM,10886.33,0.42,56350.58,94208.29,12.12,2.37,1.36,8.12,20.26,28.31
35,2010-12-30 12:00:00 AM,10886.33,0.51,56350.58,94208.29,10.15,1.99,1.17,6.80,20.26,28.31
36,2010-09-30 12:00:00 AM,10362.86,0.58,53135.29,90542.54,9.33,1.84,1.07,6.19,28.15,43.59
37,2010-06-30 12:00:00 AM,7844.26,0.67,48263.55,81094.15,8.96,1.72,0.99,5.98,11.38,66.37

In [96]:
url_2 = "http://www.wiseindex.com/DataCenter/GridData?currentPage=1&endDT=2019-11-06&fromDT=2010-05-07&index_ids=WGI0002T&isEnd=1&itemType=1&perPage=100&term=4"

In [97]:
rqt = urlopen(url_2) #request
datat = json.loads(rqt.read().decode()) #JSON 파싱 후
df2 = json_normalize(datat) #1페이지 -> to_dataframe

In [98]:
df2

,IDX1_VAL1,IDX1_VAL2,IDX1_VAL3,ROW_IDX,TOT_ROW,TRD_DT
0,9264.97,5.979213e+07,201057.57,1,38,/Date(1569769200000)/
1,9326.58,5.970247e+07,201636.54,2,38,/Date(1561647600000)/
2,8214.21,5.254692e+07,296338.75,3,38,/Date(1553785200000)/
3,7963.47,5.119446e+07,187204.46,4,38,/Date(1545922800000)/
4,8984.04,5.775537e+07,305982.54,5,38,/Date(1538060400000)/
5,8334.54,5.383633e+07,446132.51,6,38,/Date(1530198000000)/
6,8955.52,5.769653e+07,543273.58,7,38,/Date(1522335600000)/
7,9560.53,6.159436e+07,178863.22,8,38,/Date(1514386800000)/
8,9090.96,5.856913e+07,288537.23,9,38,/Date(1506610800000)/
9,9924.32,6.690497e+07,234549.13,10,38,/Date(1498748400000)/
10,9689.86,6.523103e+07,254037.19,11,38,/Date(1490886000000)/
11,9655.76,6.500148e+07,161625.61,12,38,/Date(1482937200000)/
12,9673.04,6.511776e+07,269609.44,13,38,/Date(1475161200000)/
13,9319.34,6.273674e+07,600172.63,14,38,/Date(1467212400000)/
14,10187.66,6.858214e+07,298859.74,15,38,/Date(1459350000000)/
15,10018.62,6.706907e+07,171459.28,16,38,/Date(1451401200000)/
16,10463.91,7.005001e+07,448167.00,17,38,/Date(1443538800000)/
17,9466.62,6.255421e+07,299086.61,18,38,/Date(1435590000000)/
18,10913.81,7.211711e+07,322339.21,19,38,/Date(1427727600000)/
19,11148.39,7.230805e+07,250370.19,20,38,/Date(1419865200000)/
20,12483.88,8.053648e+07,329548.43,21,38,/Date(1412002800000)/
21,13659.73,8.686042e+07,328188.35,22,38,/Date(1404054000000)/
22,14403.12,9.158754e+07,373037.45,23,38,/Date(1396191600000)/
23,13923.96,8.884672e+07,295138.63,24,38,/Date(1388329200000)/
24,14495.80,9.213430e+07,349559.73,25,38,/Date(1380466800000)/
25,13269.07,8.433728e+07,586416.35,26,38,/Date(1372345200000)/
26,13584.76,8.634374e+07,278297.25,27,38,/Date(1364482800000)/
27,13536.72,8.603843e+07,401440.26,28,38,/Date(1356620400000)/
28,15191.10,9.619365e+07,549832.68,29,38,/Date(1348758000000)/
29,14341.02,9.081071e+07,521272.88,30,38,/Date(1340895600000)/
30,14699.90,9.287540e+07,586929.69,31,38,/Date(1333033200000)/
31,13730.27,8.651167e+07,270789.07,32,38,/Date(1325084400000)/
32,14337.97,8.975554e+07,669725.26,33,38,/Date(1317308400000)/
33,16344.36,1.022750e+08,746004.66,34,38,/Date(1309359600000)/
34,14269.71,8.358767e+07,907996.03,35,38,/Date(1301497200000)/
35,11956.38,6.920797e+07,429644.99,36,38,/Date(1293634800000)/
36,10389.62,6.004844e+07,396146.85,37,38,/Date(1285772400000)/
37,9055.56,5.231192e+07,358489.93,38,38,/Date(1277823600000)/

In [99]:
for i in range(0, len(df2)):

    d = df2['TRD_DT'].iloc[i][6:-2]
    d = int(d[:10])
    d = datetime.fromtimestamp(d).strftime('%Y-%m-%d %I:%M:%S %p')
    df2['TRD_DT'].iloc[i] = d

C:\Users\ASUS\Anaconda3\lib\site-packages\pandas\core\indexing.py:190: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._setitem_with_indexer(indexer, value)

In [100]:
df2

,IDX1_VAL1,IDX1_VAL2,IDX1_VAL3,ROW_IDX,TOT_ROW,TRD_DT
0,9264.97,5.979213e+07,201057.57,1,38,2019-09-30 12:00:00 AM
1,9326.58,5.970247e+07,201636.54,2,38,2019-06-28 12:00:00 AM
2,8214.21,5.254692e+07,296338.75,3,38,2019-03-29 12:00:00 AM
3,7963.47,5.119446e+07,187204.46,4,38,2018-12-28 12:00:00 AM
4,8984.04,5.775537e+07,305982.54,5,38,2018-09-28 12:00:00 AM
5,8334.54,5.383633e+07,446132.51,6,38,2018-06-29 12:00:00 AM
6,8955.52,5.769653e+07,543273.58,7,38,2018-03-30 12:00:00 AM
7,9560.53,6.159436e+07,178863.22,8,38,2017-12-28 12:00:00 AM
8,9090.96,5.856913e+07,288537.23,9,38,2017-09-29 12:00:00 AM
9,9924.32,6.690497e+07,234549.13,10,38,2017-06-30 12:00:00 AM
10,9689.86,6.523103e+07,254037.19,11,38,2017-03-31 12:00:00 AM
11,9655.76,6.500148e+07,161625.61,12,38,2016-12-29 12:00:00 AM
12,9673.04,6.511776e+07,269609.44,13,38,2016-09-30 12:00:00 AM
13,9319.34,6.273674e+07,600172.63,14,38,2016-06-30 12:00:00 AM
14,10187.66,6.858214e+07,298859.74,15,38,2016-03-31 12:00:00 AM
15,10018.62,6.706907e+07,171459.28,16,38,2015-12-30 12:00:00 AM
16,10463.91,7.005001e+07,448167.00,17,38,2015-09-30 12:00:00 AM
17,9466.62,6.255421e+07,299086.61,18,38,2015-06-30 12:00:00 AM
18,10913.81,7.211711e+07,322339.21,19,38,2015-03-31 12:00:00 AM
19,11148.39,7.230805e+07,250370.19,20,38,2014-12-30 12:00:00 AM
20,12483.88,8.053648e+07,329548.43,21,38,2014-09-30 12:00:00 AM
21,13659.73,8.686042e+07,328188.35,22,38,2014-06-30 12:00:00 AM
22,14403.12,9.158754e+07,373037.45,23,38,2014-03-31 12:00:00 AM
23,13923.96,8.884672e+07,295138.63,24,38,2013-12-30 12:00:00 AM
24,14495.80,9.213430e+07,349559.73,25,38,2013-09-30 12:00:00 AM
25,13269.07,8.433728e+07,586416.35,26,38,2013-06-28 12:00:00 AM
26,13584.76,8.634374e+07,278297.25,27,38,2013-03-29 12:00:00 AM
27,13536.72,8.603843e+07,401440.26,28,38,2012-12-28 12:00:00 AM
28,15191.10,9.619365e+07,549832.68,29,38,2012-09-28 12:00:00 AM
29,14341.02,9.081071e+07,521272.88,30,38,2012-06-29 12:00:00 AM
30,14699.90,9.287540e+07,586929.69,31,38,2012-03-30 12:00:00 AM
31,13730.27,8.651167e+07,270789.07,32,38,2011-12-29 12:00:00 AM
32,14337.97,8.975554e+07,669725.26,33,38,2011-09-30 12:00:00 AM
33,16344.36,1.022750e+08,746004.66,34,38,2011-06-30 12:00:00 AM
34,14269.71,8.358767e+07,907996.03,35,38,2011-03-31 12:00:00 AM
35,11956.38,6.920797e+07,429644.99,36,38,2010-12-30 12:00:00 AM
36,10389.62,6.004844e+07,396146.85,37,38,2010-09-30 12:00:00 AM
37,9055.56,5.231192e+07,358489.93,38,38,2010-06-30 12:00:00 AM

In [101]:
del df2['ROW_IDX']
del df2['TOT_ROW']

In [102]:
df2.rename(columns={'TRD_DT':"Date"}, inplace=True)

In [103]:
title = {"IDX1_VAL1": "index_value",
"IDX1_VAL2": "cap",
"IDX1_VAL3": "transaction"}

In [104]:
df2.rename(columns=title, inplace=True)

In [105]:
a = list(df2.columns)[:-1]
a.insert(0, 'Date')
a

['Date', 'index_value', 'cap', 'transaction']

In [106]:
df2 = df2[a]

In [107]:
df2

                      Date  index_value           cap  transaction
0   2019-09-30 12:00:00 AM      9264.97  5.979213e+07    201057.57
1   2019-06-28 12:00:00 AM      9326.58  5.970247e+07    201636.54
2   2019-03-29 12:00:00 AM      8214.21  5.254692e+07    296338.75
3   2018-12-28 12:00:00 AM      7963.47  5.119446e+07    187204.46
4   2018-09-28 12:00:00 AM      8984.04  5.775537e+07    305982.54
5   2018-06-29 12:00:00 AM      8334.54  5.383633e+07    446132.51
6   2018-03-30 12:00:00 AM      8955.52  5.769653e+07    543273.58
7   2017-12-28 12:00:00 AM      9560.53  6.159436e+07    178863.22
8   2017-09-29 12:00:00 AM      9090.96  5.856913e+07    288537.23
9   2017-06-30 12:00:00 AM      9924.32  6.690497e+07    234549.13
10  2017-03-31 12:00:00 AM      9689.86  6.523103e+07    254037.19
11  2016-12-29 12:00:00 AM      9655.76  6.500148e+07    161625.61
12  2016-09-30 12:00:00 AM      9673.04  6.511776e+07    269609.44
13  2016-06-30 12:00:00 AM      9319.34  6.273674e+07    600172.63
14  2016-03-31 12:00:00 AM     10187.66  6.858214e+07    298859.74
15  2015-12-30 12:00:00 AM     10018.62  6.706907e+07    171459.28
16  2015-09-30 12:00:00 AM     10463.91  7.005001e+07    448167.00
17  2015-06-30 12:00:00 AM      9466.62  6.255421e+07    299086.61
18  2015-03-31 12:00:00 AM     10913.81  7.211711e+07    322339.21
19  2014-12-30 12:00:00 AM     11148.39  7.230805e+07    250370.19
20  2014-09-30 12:00:00 AM     12483.88  8.053648e+07    329548.43
21  2014-06-30 12:00:00 AM     13659.73  8.686042e+07    328188.35
22  2014-03-31 12:00:00 AM     14403.12  9.158754e+07    373037.45
23  2013-12-30 12:00:00 AM     13923.96  8.884672e+07    295138.63
24  2013-09-30 12:00:00 AM     14495.80  9.213430e+07    349559.73
25  2013-06-28 12:00:00 AM     13269.07  8.433728e+07    586416.35
26  2013-03-29 12:00:00 AM     13584.76  8.634374e+07    278297.25
27  2012-12-28 12:00:00 AM     13536.72  8.603843e+07    401440.26
28  2012-09-28 12:00:00 AM     15191.10  9.619365e+07    549832.68
29  2012-06-29 12:00:00 AM     14341.02  9.081071e+07    521272.88
30  2012-03-30 12:00:00 AM     14699.90  9.287540e+07    586929.69
31  2011-12-29 12:00:00 AM     13730.27  8.651167e+07    270789.07
32  2011-09-30 12:00:00 AM     14337.97  8.975554e+07    669725.26
33  2011-06-30 12:00:00 AM     16344.36  1.022750e+08    746004.66
34  2011-03-31 12:00:00 AM     14269.71  8.358767e+07    907996.03
35  2010-12-30 12:00:00 AM     11956.38  6.920797e+07    429644.99
36  2010-09-30 12:00:00 AM     10389.62  6.004844e+07    396146.85
37  2010-06-30 12:00:00 AM      9055.56  5.231192e+07    358489.93

In [108]:
win_loss = list()

In [109]:
for i in range(1, len(df2)):
    if df2['index_value'][i] > df2['index_value'][i-1]:
        win_loss.append('win')
    else:
        win_loss.append('loss')

In [110]:
len(win_loss)

37

In [112]:
win_loss.insert(0, "NULL")

In [114]:
df2

                      Date  index_value           cap  transaction
0   2019-09-30 12:00:00 AM      9264.97  5.979213e+07    201057.57
1   2019-06-28 12:00:00 AM      9326.58  5.970247e+07    201636.54
2   2019-03-29 12:00:00 AM      8214.21  5.254692e+07    296338.75
3   2018-12-28 12:00:00 AM      7963.47  5.119446e+07    187204.46
4   2018-09-28 12:00:00 AM      8984.04  5.775537e+07    305982.54
5   2018-06-29 12:00:00 AM      8334.54  5.383633e+07    446132.51
6   2018-03-30 12:00:00 AM      8955.52  5.769653e+07    543273.58
7   2017-12-28 12:00:00 AM      9560.53  6.159436e+07    178863.22
8   2017-09-29 12:00:00 AM      9090.96  5.856913e+07    288537.23
9   2017-06-30 12:00:00 AM      9924.32  6.690497e+07    234549.13
10  2017-03-31 12:00:00 AM      9689.86  6.523103e+07    254037.19
11  2016-12-29 12:00:00 AM      9655.76  6.500148e+07    161625.61
12  2016-09-30 12:00:00 AM      9673.04  6.511776e+07    269609.44
13  2016-06-30 12:00:00 AM      9319.34  6.273674e+07    600172.63
14  2016-03-31 12:00:00 AM     10187.66  6.858214e+07    298859.74
15  2015-12-30 12:00:00 AM     10018.62  6.706907e+07    171459.28
16  2015-09-30 12:00:00 AM     10463.91  7.005001e+07    448167.00
17  2015-06-30 12:00:00 AM      9466.62  6.255421e+07    299086.61
18  2015-03-31 12:00:00 AM     10913.81  7.211711e+07    322339.21
19  2014-12-30 12:00:00 AM     11148.39  7.230805e+07    250370.19
20  2014-09-30 12:00:00 AM     12483.88  8.053648e+07    329548.43
21  2014-06-30 12:00:00 AM     13659.73  8.686042e+07    328188.35
22  2014-03-31 12:00:00 AM     14403.12  9.158754e+07    373037.45
23  2013-12-30 12:00:00 AM     13923.96  8.884672e+07    295138.63
24  2013-09-30 12:00:00 AM     14495.80  9.213430e+07    349559.73
25  2013-06-28 12:00:00 AM     13269.07  8.433728e+07    586416.35
26  2013-03-29 12:00:00 AM     13584.76  8.634374e+07    278297.25
27  2012-12-28 12:00:00 AM     13536.72  8.603843e+07    401440.26
28  2012-09-28 12:00:00 AM     15191.10  9.619365e+07    549832.68
29  2012-06-29 12:00:00 AM     14341.02  9.081071e+07    521272.88
30  2012-03-30 12:00:00 AM     14699.90  9.287540e+07    586929.69
31  2011-12-29 12:00:00 AM     13730.27  8.651167e+07    270789.07
32  2011-09-30 12:00:00 AM     14337.97  8.975554e+07    669725.26
33  2011-06-30 12:00:00 AM     16344.36  1.022750e+08    746004.66
34  2011-03-31 12:00:00 AM     14269.71  8.358767e+07    907996.03
35  2010-12-30 12:00:00 AM     11956.38  6.920797e+07    429644.99
36  2010-09-30 12:00:00 AM     10389.62  6.004844e+07    396146.85
37  2010-06-30 12:00:00 AM      9055.56  5.231192e+07    358489.93

In [115]:
df2['win_loss'] = win_loss

C:\Users\ASUS\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [116]:
df2

                      Date  index_value           cap  transaction win_loss
0   2019-09-30 12:00:00 AM      9264.97  5.979213e+07    201057.57     NULL
1   2019-06-28 12:00:00 AM      9326.58  5.970247e+07    201636.54      win
2   2019-03-29 12:00:00 AM      8214.21  5.254692e+07    296338.75     loss
3   2018-12-28 12:00:00 AM      7963.47  5.119446e+07    187204.46     loss
4   2018-09-28 12:00:00 AM      8984.04  5.775537e+07    305982.54      win
5   2018-06-29 12:00:00 AM      8334.54  5.383633e+07    446132.51     loss
6   2018-03-30 12:00:00 AM      8955.52  5.769653e+07    543273.58      win
7   2017-12-28 12:00:00 AM      9560.53  6.159436e+07    178863.22      win
8   2017-09-29 12:00:00 AM      9090.96  5.856913e+07    288537.23     loss
9   2017-06-30 12:00:00 AM      9924.32  6.690497e+07    234549.13      win
10  2017-03-31 12:00:00 AM      9689.86  6.523103e+07    254037.19     loss
11  2016-12-29 12:00:00 AM      9655.76  6.500148e+07    161625.61     loss
12  2016-09-30 12:00:00 AM      9673.04  6.511776e+07    269609.44      win
13  2016-06-30 12:00:00 AM      9319.34  6.273674e+07    600172.63     loss
14  2016-03-31 12:00:00 AM     10187.66  6.858214e+07    298859.74      win
15  2015-12-30 12:00:00 AM     10018.62  6.706907e+07    171459.28     loss
16  2015-09-30 12:00:00 AM     10463.91  7.005001e+07    448167.00      win
17  2015-06-30 12:00:00 AM      9466.62  6.255421e+07    299086.61     loss
18  2015-03-31 12:00:00 AM     10913.81  7.211711e+07    322339.21      win
19  2014-12-30 12:00:00 AM     11148.39  7.230805e+07    250370.19      win
20  2014-09-30 12:00:00 AM     12483.88  8.053648e+07    329548.43      win
21  2014-06-30 12:00:00 AM     13659.73  8.686042e+07    328188.35      win
22  2014-03-31 12:00:00 AM     14403.12  9.158754e+07    373037.45      win
23  2013-12-30 12:00:00 AM     13923.96  8.884672e+07    295138.63     loss
24  2013-09-30 12:00:00 AM     14495.80  9.213430e+07    349559.73      win
25  2013-06-28 12:00:00 AM     13269.07  8.433728e+07    586416.35     loss
26  2013-03-29 12:00:00 AM     13584.76  8.634374e+07    278297.25      win
27  2012-12-28 12:00:00 AM     13536.72  8.603843e+07    401440.26     loss
28  2012-09-28 12:00:00 AM     15191.10  9.619365e+07    549832.68      win
29  2012-06-29 12:00:00 AM     14341.02  9.081071e+07    521272.88     loss
30  2012-03-30 12:00:00 AM     14699.90  9.287540e+07    586929.69      win
31  2011-12-29 12:00:00 AM     13730.27  8.651167e+07    270789.07     loss
32  2011-09-30 12:00:00 AM     14337.97  8.975554e+07    669725.26      win
33  2011-06-30 12:00:00 AM     16344.36  1.022750e+08    746004.66      win
34  2011-03-31 12:00:00 AM     14269.71  8.358767e+07    907996.03     loss
35  2010-12-30 12:00:00 AM     11956.38  6.920797e+07    429644.99     loss
36  2010-09-30 12:00:00 AM     10389.62  6.004844e+07    396146.85     loss
37  2010-06-30 12:00:00 AM      9055.56  5.231192e+07    358489.93     loss

In [117]:
df1

,Date,EPS (Earnings per share),배당수익률(FY0),BPS (Book Value),SPS (Sales),PER(Price-Earnings Ratio),PBR,PSR,EV/EVITDA,매출액 Growth,영업이익 Growth
0,2019-09-30 12:00:00 AM,5373.97,2.05,140875.01,220419.45,15.40,0.60,0.38,8.05,6.13,16.56
1,2019-06-28 12:00:00 AM,4665.74,2.03,136580.81,212584.34,16.50,0.62,0.38,8.34,5.12,-6.01
2,2019-03-29 12:00:00 AM,5214.58,2.20,137447.43,209505.05,13.89,0.54,0.35,7.65,1.01,-34.26
3,2018-12-28 12:00:00 AM,5214.58,2.26,137447.43,209505.05,13.51,0.53,0.34,7.61,1.01,-34.26
4,2018-09-28 12:00:00 AM,5444.26,2.01,137351.29,208695.41,14.53,0.59,0.38,8.16,4.15,-13.95
5,2018-06-29 12:00:00 AM,6848.96,2.15,135859.22,209162.56,13.42,0.56,0.36,7.67,-3.60,-38.17
6,2018-03-30 12:00:00 AM,8013.05,2.14,136359.36,211124.64,9.98,0.60,0.38,6.92,7.97,-31.33
7,2017-12-28 12:00:00 AM,8013.05,2.01,136359.36,211124.64,10.67,0.64,0.41,7.23,7.97,-31.33
8,2017-09-29 12:00:00 AM,9339.86,2.11,134923.97,207203.40,8.75,0.62,0.39,6.36,-4.03,-28.68
9,2017-06-30 12:00:00 AM,11119.13,1.93,132289.19,207643.28,8.28,0.70,0.43,6.08,0.78,-13.44
10,2017-03-31 12:00:00 AM,11781.20,1.98,127370.78,207221.78,7.38,0.70,0.42,5.64,-3.36,-15.08
11,2016-12-29 12:00:00 AM,11781.20,1.98,127370.78,207221.78,7.34,0.70,0.42,5.62,-3.36,-15.08
12,2016-09-30 12:00:00 AM,11386.23,1.97,126239.00,208935.86,7.67,0.71,0.42,5.97,8.72,6.42
13,2016-06-30 12:00:00 AM,11522.82,2.05,121748.73,204423.79,7.33,0.70,0.41,6.01,6.86,-16.16
14,2016-03-31 12:00:00 AM,11762.47,1.53,120526.57,201661.75,7.79,0.78,0.46,6.23,8.64,-1.09
15,2015-12-30 12:00:00 AM,11762.47,1.55,120526.57,201661.75,7.69,0.77,0.45,6.17,8.64,-1.09
16,2015-09-30 12:00:00 AM,12297.27,1.48,116633.86,197890.07,7.65,0.82,0.49,5.92,-0.01,-11.21
17,2015-06-30 12:00:00 AM,13437.74,1.64,111528.82,196771.32,6.35,0.77,0.43,5.11,10.79,7.47
18,2015-03-31 12:00:00 AM,15424.97,0.99,109223.91,191006.91,6.30,0.91,0.51,5.08,2.52,-9.13
19,2014-12-30 12:00:00 AM,15424.97,0.95,109223.91,191006.91,6.55,0.94,0.53,5.24,2.52,-9.13
20,2014-09-30 12:00:00 AM,17621.31,0.86,112825.84,199915.97,6.71,1.07,0.59,5.41,0.53,-8.23
21,2014-06-30 12:00:00 AM,17131.79,0.80,106564.65,199387.32,7.31,1.20,0.64,5.88,1.75,13.96
22,2014-03-31 12:00:00 AM,15577.18,0.74,98934.36,198535.59,8.40,1.34,0.67,6.30,3.81,0.93
23,2013-12-30 12:00:00 AM,15577.18,0.77,98934.36,198535.59,8.07,1.29,0.65,6.10,3.81,0.93
24,2013-09-30 12:00:00 AM,15250.86,0.74,95489.02,192766.73,8.48,1.38,0.67,6.32,4.89,-5.37
25,2013-06-28 12:00:00 AM,16172.96,0.81,87911.77,187372.62,7.73,1.32,0.62,5.93,0.73,-17.74
26,2013-03-29 12:00:00 AM,16110.80,0.74,85771.17,187235.15,7.43,1.42,0.64,5.65,8.40,-3.37
27,2012-12-28 12:00:00 AM,16110.80,0.74,85771.17,187235.15,7.42,1.41,0.64,5.65,8.40,-3.37
28,2012-09-28 12:00:00 AM,15294.33,0.66,81746.03,183924.24,8.75,1.66,0.73,6.56,9.85,12.63
29,2012-06-29 12:00:00 AM,14453.93,0.69,74232.56,174916.42,8.31,1.65,0.70,6.33,33.72,32.13
30,2012-03-30 12:00:00 AM,13809.86,0.58,71863.04,415111.45,9.38,1.83,1.00,19.03,28.21,48.87
31,2011-12-29 12:00:00 AM,13809.86,0.62,71863.04,415111.45,8.76,1.71,0.94,17.94,28.21,48.87
32,2011-09-30 12:00:00 AM,13647.70,0.60,69150.10,390218.09,9.23,1.84,0.92,15.52,21.01,32.41
33,2011-06-30 12:00:00 AM,11601.11,0.53,59648.70,97734.41,11.80,2.26,0.99,15.99,16.08,26.35
34,2011-03-31 12:00:00 AM,10886.33,0.42,56350.58,94208.29,12.12,2.37,1.36,8.12,20.26,28.31
35,2010-12-30 12:00:00 AM,10886.33,0.51,56350.58,94208.29,10.15,1.99,1.17,6.80,20.26,28.31
36,2010-09-30 12:00:00 AM,10362.86,0.58,53135.29,90542.54,9.33,1.84,1.07,6.19,28.15,43.59
37,2010-06-30 12:00:00 AM,7844.26,0.67,48263.55,81094.15,8.96,1.72,0.99,5.98,11.38,66.37

In [35]:
table = pd.merge(df1, df2, on='Date')

In [36]:
table

,Date,EPS (Earnings per share),배당수익률(FY0),BPS (Book Value),SPS (Sales),PER(Price-Earnings Ratio),PBR,PSR,EV/EVITDA,매출액 Growth,영업이익 Growth,index_value,cap,transaction,win_loss
0,2019-09-30 12:00:00 AM,5373.97,2.05,140875.01,220419.45,15.40,0.60,0.38,8.05,6.13,16.56,9264.97,5.979213e+07,201057.57,NULL
1,2019-06-28 12:00:00 AM,4665.74,2.03,136580.81,212584.34,16.50,0.62,0.38,8.34,5.12,-6.01,9326.58,5.970247e+07,201636.54,win
2,2019-03-29 12:00:00 AM,5214.58,2.20,137447.43,209505.05,13.89,0.54,0.35,7.65,1.01,-34.26,8214.21,5.254692e+07,296338.75,loss
3,2018-12-28 12:00:00 AM,5214.58,2.26,137447.43,209505.05,13.51,0.53,0.34,7.61,1.01,-34.26,7963.47,5.119446e+07,187204.46,loss
4,2018-09-28 12:00:00 AM,5444.26,2.01,137351.29,208695.41,14.53,0.59,0.38,8.16,4.15,-13.95,8984.04,5.775537e+07,305982.54,win
5,2018-06-29 12:00:00 AM,6848.96,2.15,135859.22,209162.56,13.42,0.56,0.36,7.67,-3.60,-38.17,8334.54,5.383633e+07,446132.51,loss
6,2018-03-30 12:00:00 AM,8013.05,2.14,136359.36,211124.64,9.98,0.60,0.38,6.92,7.97,-31.33,8955.52,5.769653e+07,543273.58,win
7,2017-12-28 12:00:00 AM,8013.05,2.01,136359.36,211124.64,10.67,0.64,0.41,7.23,7.97,-31.33,9560.53,6.159436e+07,178863.22,win
8,2017-09-29 12:00:00 AM,9339.86,2.11,134923.97,207203.40,8.75,0.62,0.39,6.36,-4.03,-28.68,9090.96,5.856913e+07,288537.23,loss
9,2017-06-30 12:00:00 AM,11119.13,1.93,132289.19,207643.28,8.28,0.70,0.43,6.08,0.78,-13.44,9924.32,6.690497e+07,234549.13,win
10,2017-03-31 12:00:00 AM,11781.20,1.98,127370.78,207221.78,7.38,0.70,0.42,5.64,-3.36,-15.08,9689.86,6.523103e+07,254037.19,loss
11,2016-12-29 12:00:00 AM,11781.20,1.98,127370.78,207221.78,7.34,0.70,0.42,5.62,-3.36,-15.08,9655.76,6.500148e+07,161625.61,loss
12,2016-09-30 12:00:00 AM,11386.23,1.97,126239.00,208935.86,7.67,0.71,0.42,5.97,8.72,6.42,9673.04,6.511776e+07,269609.44,win
13,2016-06-30 12:00:00 AM,11522.82,2.05,121748.73,204423.79,7.33,0.70,0.41,6.01,6.86,-16.16,9319.34,6.273674e+07,600172.63,loss
14,2016-03-31 12:00:00 AM,11762.47,1.53,120526.57,201661.75,7.79,0.78,0.46,6.23,8.64,-1.09,10187.66,6.858214e+07,298859.74,win
15,2015-12-30 12:00:00 AM,11762.47,1.55,120526.57,201661.75,7.69,0.77,0.45,6.17,8.64,-1.09,10018.62,6.706907e+07,171459.28,loss
16,2015-09-30 12:00:00 AM,12297.27,1.48,116633.86,197890.07,7.65,0.82,0.49,5.92,-0.01,-11.21,10463.91,7.005001e+07,448167.00,win
17,2015-06-30 12:00:00 AM,13437.74,1.64,111528.82,196771.32,6.35,0.77,0.43,5.11,10.79,7.47,9466.62,6.255421e+07,299086.61,loss
18,2015-03-31 12:00:00 AM,15424.97,0.99,109223.91,191006.91,6.30,0.91,0.51,5.08,2.52,-9.13,10913.81,7.211711e+07,322339.21,win
19,2014-12-30 12:00:00 AM,15424.97,0.95,109223.91,191006.91,6.55,0.94,0.53,5.24,2.52,-9.13,11148.39,7.230805e+07,250370.19,win
20,2014-09-30 12:00:00 AM,17621.31,0.86,112825.84,199915.97,6.71,1.07,0.59,5.41,0.53,-8.23,12483.88,8.053648e+07,329548.43,win
21,2014-06-30 12:00:00 AM,17131.79,0.80,106564.65,199387.32,7.31,1.20,0.64,5.88,1.75,13.96,13659.73,8.686042e+07,328188.35,win
22,2014-03-31 12:00:00 AM,15577.18,0.74,98934.36,198535.59,8.40,1.34,0.67,6.30,3.81,0.93,14403.12,9.158754e+07,373037.45,win
23,2013-12-30 12:00:00 AM,15577.18,0.77,98934.36,198535.59,8.07,1.29,0.65,6.10,3.81,0.93,13923.96,8.884672e+07,295138.63,loss
24,2013-09-30 12:00:00 AM,15250.86,0.74,95489.02,192766.73,8.48,1.38,0.67,6.32,4.89,-5.37,14495.80,9.213430e+07,349559.73,win
25,2013-06-28 12:00:00 AM,16172.96,0.81,87911.77,187372.62,7.73,1.32,0.62,5.93,0.73,-17.74,13269.07,8.433728e+07,586416.35,loss
26,2013-03-29 12:00:00 AM,16110.80,0.74,85771.17,187235.15,7.43,1.42,0.64,5.65,8.40,-3.37,13584.76,8.634374e+07,278297.25,win
27,2012-12-28 12:00:00 AM,16110.80,0.74,85771.17,187235.15,7.42,1.41,0.64,5.65,8.40,-3.37,13536.72,8.603843e+07,401440.26,loss
28,2012-09-28 12:00:00 AM,15294.33,0.66,81746.03,183924.24,8.75,1.66,0.73,6.56,9.85,12.63,15191.10,9.619365e+07,549832.68,win
29,2012-06-29 12:00:00 AM,14453.93,0.69,74232.56,174916.42,8.31,1.65,0.70,6.33,33.72,32.13,14341.02,9.081071e+07,521272.88,loss
30,2012-03-30 12:00:00 AM,13809.86,0.58,71863.04,415111.45,9.38,1.83,1.00,19.03,28.21,48.87,14699.90,9.287540e+07,586929.69,win
31,2011-12-29 12:00:00 AM,13809.86,0.62,71863.04,415111.45,8.76,1.71,0.94,17.94,28.21,48.87,13730.27,8.651167e+07,270789.07,loss
32,2011-09-30 12:00:00 AM,13647.70,0.60,69150.10,390218.09,9.23,1.84,0.92,15.52,21.01,32.41,14337.97,8.975554e+07,669725.26,win
33,2011-06-30 12:00:00 AM,11601.11,0.53,59648.70,97734.41,11.80,2.26,0.99,15.99,16.08,26.35,16344.36,1.022750e+08,746004.66,win
34,2011-03-31 12:00:00 AM,10886.33,0.42,56350.58,94208.29,12.12,2.37,1.36,8.12,20.26,28.31,14269.71,8.358767e+07,907996.03,loss
35,2010-12-30 12:00:00 AM,10886.33,0.51,56350.58,94208.29,10.15,1.99,1.17,6.80,20.26,28.31,11956.38,6.920797e+07,429644.99,loss
36,2010-09-30 12:00:00 AM,10362.86,0.58,53135.29,90542.54,9.33,1.84,1.07,6.19,28.15,43.59,10389.62,6.004844e+07,396146.85,loss
37,2010-06-30 12:00:00 AM,7844.26,0.67,48263.55,81094.15,8.96,1.72,0.99,5.98,11.38,66.37,9055.56,5.231192e+07,358489.93,loss

In [39]:
table.to_csv("hyundai.csv")

In [247]:
rate_table = table.copy()

In [248]:
rate_list = list(rate_table.columns)

In [249]:
rate_list

['Date',
 'EPS (Earnings per share)',
 '배당수익률(FY0)',
 'BPS (Book Value)',
 'SPS (Sales)',
 'PER(Price-Earnings Ratio)',
 'PBR',
 'PSR',
 'EV/EVITDA',
 '매출액 Growth',
 '영업이익 Growth',
 'index_value',
 'cap',
 'transaction',
 'win_loss']

In [250]:
real_rate_list = list()
real_rate_list.append(rate_list[1])
real_rate_list.append(rate_list[2])
real_rate_list.append(rate_list[3])
real_rate_list.append(rate_list[5])

In [251]:
real_rate_list

['EPS (Earnings per share)',
 '배당수익률(FY0)',
 'BPS (Book Value)',
 'PER(Price-Earnings Ratio)']

In [252]:
test_table = rate_table[real_rate_list]

In [253]:
len(test_table)

38

In [254]:
test_table_copy = test_table.copy()

In [255]:
for i in range(len(real_rate_list)):
    for j in range(len(test_table_copy)-1,0, -1):
        value = ((test_table[real_rate_list[i]][j-1] - test_table[real_rate_list[i]][j]) / test_table[real_rate_list[i]][j-1]) * 100
        test_table_copy[real_rate_list[i]][j-1] = value

In [256]:
test_table_copy.insert(loc=0, column='Date', value=table['Date'])

In [261]:
test_table_copy.insert(loc=5, column='total_revenue', value = table['매출액 Growth'])

In [262]:
test_table_copy.insert(loc=6, column='total_profit', value = table['영업이익 Growth'])

In [275]:
test_table_copy.drop(index=len(test_table_copy)-1, inplace=True)

In [281]:
test_table_copy.rename(columns={"배당수익률(FY0)" : "Divedend yield ratio"}, inplace=True)

In [284]:
test_table_copy.to_csv('final.csv')