In [44]:
import pandas as pd
import numpy as np
from scipy.stats.mstats import winsorize
from sklearn.naive_bayes import GaussianNB

In [45]:
df = pd.read_csv("total_me_data.csv")

In [46]:
# back_Test용만 뺀다.
back_test_df = df.query('Date == "2019-06-28 0:00" | Date == "2019-09-30 0:00" | Date == "2019-03-29 0:00" |  Date == "2018-12-28 0:00"')

# Model Training

In [47]:
# bacK_test 용은 삭제
df.drop(back_test_df.isin(df).index, inplace=True)

In [48]:
df.drop('MA',1)

,Name,Date,MA,EPS,BPS,SPS,PER,PBR,PSR,EV/EBITDA,Profit Growth,Revenue Growth,FYO growth,W/L
4,gs_05,2018-09-28 0:00,7761.897000,6008.07,2.01,63449.08,187779.20,9.98,0.93,0.32,6.58,16.40,52.38,0
5,gs_06,2018-06-29 0:00,8391.907333,4670.14,2.08,63369.49,175621.62,11.37,0.94,0.32,6.87,7.79,7.82,0
6,gs_07,2018-03-30 0:00,9534.585000,5640.90,2.30,63165.87,172444.17,9.29,0.83,0.30,7.07,19.80,17.02,1
7,gs_08,2017-12-28 0:00,9480.621667,5640.90,2.19,63165.87,172444.17,9.74,0.87,0.32,7.26,19.80,17.02,0
8,gs_09,2017-09-29 0:00,9512.247000,5363.76,2.23,61484.40,165063.66,10.08,0.89,0.33,7.39,13.80,-8.70,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
291,sk_33,2011-09-30 0:00,14556.122000,7932.23,2.24,64119.48,111168.07,8.81,1.09,0.41,8.19,14.46,2.09,0
292,sk_34,2011-06-30 0:00,16118.153330,6050.78,1.88,57476.29,135655.58,10.75,1.32,0.54,7.51,16.25,284.22,1
293,sk_35,2011-03-31 0:00,15519.313000,4719.74,1.90,57416.02,130684.69,16.70,1.40,0.60,8.57,9.81,40.30,1
294,sk_36,2010-12-30 0:00,12726.086000,4719.74,1.98,57416.02,130684.69,16.07,1.35,0.58,8.30,9.81,40.30,1
295,sk_37,2010-09-30 0:00,11140.297000,4267.69,2.21,55807.88,128028.48,15.89,1.24,0.53,8.08,15.76,46.56,1

In [39]:
#features_treain, labels_train
train_set = df # df는 전체 train_set
features_train = winsorize(train_set.iloc[:, 2:8], 0.05)
labels_train = winsorize(train_set.iloc[:, 8:], 0.05)

,Name,Date,MA,EPS,BPS,SPS,PER,PBR,PSR,EV/EBITDA,Profit Growth,Revenue Growth,FYO growth,W/L
4,gs_05,2018-09-28 0:00,7761.897000,6008.07,2.01,63449.08,187779.20,9.98,0.93,0.32,6.58,16.40,52.38,0
5,gs_06,2018-06-29 0:00,8391.907333,4670.14,2.08,63369.49,175621.62,11.37,0.94,0.32,6.87,7.79,7.82,0
6,gs_07,2018-03-30 0:00,9534.585000,5640.90,2.30,63165.87,172444.17,9.29,0.83,0.30,7.07,19.80,17.02,1
7,gs_08,2017-12-28 0:00,9480.621667,5640.90,2.19,63165.87,172444.17,9.74,0.87,0.32,7.26,19.80,17.02,0
8,gs_09,2017-09-29 0:00,9512.247000,5363.76,2.23,61484.40,165063.66,10.08,0.89,0.33,7.39,13.80,-8.70,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
291,sk_33,2011-09-30 0:00,14556.122000,7932.23,2.24,64119.48,111168.07,8.81,1.09,0.41,8.19,14.46,2.09,0
292,sk_34,2011-06-30 0:00,16118.153330,6050.78,1.88,57476.29,135655.58,10.75,1.32,0.54,7.51,16.25,284.22,1
293,sk_35,2011-03-31 0:00,15519.313000,4719.74,1.90,57416.02,130684.69,16.70,1.40,0.60,8.57,9.81,40.30,1
294,sk_36,2010-12-30 0:00,12726.086000,4719.74,1.98,57416.02,130684.69,16.07,1.35,0.58,8.30,9.81,40.30,1
295,sk_37,2010-09-30 0:00,11140.297000,4267.69,2.21,55807.88,128028.48,15.89,1.24,0.53,8.08,15.76,46.56,1

In [42]:
#Classifier 선언
clf = GaussianNB()
#fit 함수가 training sample을 이용한 학습을 진행하는 과정
clf.fit(features_train, labels_train)

ValueError: bad input shape (264, 6)