In [61]:
#데이터 핸들링, 기타
import numpy as np
import pandas as pd
import re
import math
import time
from datetime import datetime #JSON 날짜 변환

#시각화
import matplotlib.pylab as plt
import matplotlib.font_manager as fm
import seaborn as sns

#크롤링 및 JSON 핸들링
from urllib.request import urlopen
from pandas.io.json import json_normalize
import requests
import bs4
import json

# 이동평균, 주가, valuation ratio

In [96]:
# fromDT = 시작 날짜
# endDT = 끝 날짜
# perPage = 페이지당 가지고 오는 데이터 개수
# term = 일간/주간/월간/분기 를 가리키는 변수
url_index_value = "http://www.wiseindex.com/DataCenter/GridData?currentPage=1&endDT=2016-10-01&fromDT=2006-01-01&index_ids=WGI0008T&isEnd=1&itemType=1&perPage=10000&term=1"
url_valuation_ratio = "http://www.wiseindex.com/DataCenter/GridData?currentPage=1&endDT=2016-10-01&fromDT=2006-01-01&index_ids=WGI0008T&isEnd=1&itemType=3&perPage=100&term=4"
#index_value는 일간, valuation_ratio는 분기별

In [97]:
#url_index_value 처리
rqt = urlopen(url_index_value) #request
jason_data = json.loads(rqt.read().decode()) #JSON 파싱 후
index_value_df = json_normalize(jason_data) #1페이지 -> to_dataframe

#url_valuation_ratio 처리
rqt = urlopen(url_valuation_ratio) #request
jason_data = json.loads(rqt.read().decode()) #JSON 파싱 후
valuation_ratio_df = json_normalize(jason_data) #1페이지 -> to_dataframe

In [98]:
#index_value DataFrame 정리
index_value_columns = list(index_value_df.columns)
index_value_columns.remove('IDX1_VAL2')
index_value_columns.remove('IDX1_VAL3')
index_value_columns.remove('ROW_IDX')
index_value_columns.remove('TOT_ROW')
index_value_df = index_value_df.reindex(columns= index_value_columns)
#column명 수정
title_index = {"IDX1_VAL1": "Index_value",'TRD_DT':"Date"}
index_value_df.rename(columns=title_index, inplace=True) # index_value_df column명 바꾸기.

#quarter_date DataFrame 정리
valuation_ratio_columns = list(valuation_ratio_df.columns)
valuation_ratio_columns.remove('ROW_IDX')
valuation_ratio_columns.remove('TOT_ROW')
valuation_ratio_df = valuation_ratio_df.reindex(columns= valuation_ratio_columns)
#column명 수정
title = {"IDX1_VAL1": "EPS","IDX1_VAL10":"BPS","IDX1_VAL2":"SPS", "IDX1_VAL3":"PER", "IDX1_VAL4":"PBR",
       "IDX1_VAL5":"PSR", "IDX1_VAL6":"EV/EBITDA", "IDX1_VAL7":"매출액growth", "IDX1_VAL8":"영업이익growth", 
         "IDX1_VAL9":"FYO growth",'TRD_DT':"Date"}
valuation_ratio_df.rename(columns=title, inplace=True) # index_value_df column명 바꾸기.

In [99]:
# reverse 하기
index_value_df = index_value_df.iloc[::-1]

In [100]:
#30일 이동평균 계산(IDX1_VAL1)
index_value = index_value_df.iloc[:, 1] 
index_MA = index_value.rolling(window=90).mean()

##기존 dataframe에 MA column 추가
index_value_df["MA"] = pd.DataFrame({"MA":index_MA})

In [101]:
index_value_columns_new = list(index_value_df.columns)
index_value_columns_new.remove('Index_value')
index_value_df = index_value_df.reindex(columns= index_value_columns_new)

In [102]:
#'quarter_date'기준으로 dataframe 합치기
df = pd.merge(index_value_df, valuation_ratio_df, on='Date')

In [103]:
# Date 형식 바꾸기
for i in range(0, len(df)):
    d = df['Date'].iloc[i][6:-2]
    d = int(d[:10])
    d = datetime.fromtimestamp(d).strftime('%Y-%m-%d %I:%M:%S %p')
    df['Date'].iloc[i]=d

In [108]:
df = df.iloc[::-1]

# W/L 클래스 분류

In [109]:
df.head()

,Date,MA,EPS,SPS,PER,PBR,PSR,EV/EBITDA,매출액growth,영업이익growth,FYO growth,BPS
42,2016-09-30 12:00:00 AM,2588.862444,1898.81,200485.11,311158.40,55.29,0.54,0.34,10.24,-15.82,2.35,2.93
41,2016-06-30 12:00:00 AM,2553.207333,-60.91,183663.25,317093.17,65.57,0.50,0.29,9.70,-17.67,-51.47,3.22
40,2016-03-31 12:00:00 AM,2179.086667,-1944.68,183285.52,336350.55,-840.35,0.52,0.28,9.99,-14.43,-21.33,3.07
39,2015-12-30 12:00:00 AM,2136.294889,-1944.68,183285.52,336350.55,-38.14,0.41,0.22,9.86,-14.43,-21.33,3.88
38,2015-09-30 12:00:00 AM,2442.015000,1684.07,185458.96,352887.46,46.17,0.42,0.22,8.69,-9.44,-21.33,3.71

In [110]:
df_copy = df.copy() # win_loss값을 구하기 위한 copy
df_copy['W/L'] = range(len(df_copy)) # dummy값 넣기.
df_copy.head()

,Date,MA,EPS,SPS,PER,PBR,PSR,EV/EBITDA,매출액growth,영업이익growth,FYO growth,BPS,W/L
42,2016-09-30 12:00:00 AM,2588.862444,1898.81,200485.11,311158.40,55.29,0.54,0.34,10.24,-15.82,2.35,2.93,0
41,2016-06-30 12:00:00 AM,2553.207333,-60.91,183663.25,317093.17,65.57,0.50,0.29,9.70,-17.67,-51.47,3.22,1
40,2016-03-31 12:00:00 AM,2179.086667,-1944.68,183285.52,336350.55,-840.35,0.52,0.28,9.99,-14.43,-21.33,3.07,2
39,2015-12-30 12:00:00 AM,2136.294889,-1944.68,183285.52,336350.55,-38.14,0.41,0.22,9.86,-14.43,-21.33,3.88,3
38,2015-09-30 12:00:00 AM,2442.015000,1684.07,185458.96,352887.46,46.17,0.42,0.22,8.69,-9.44,-21.33,3.71,4

In [113]:
df_copy.dropna(inplace=True)

In [122]:
df_copy = df_copy.reset_index().drop('index', 1)

In [123]:
df_copy

,Date,MA,EPS,SPS,PER,PBR,PSR,EV/EBITDA,매출액growth,영업이익growth,FYO growth,BPS,W/L
0,2016-09-30 12:00:00 AM,2588.862444,1898.81,200485.11,311158.40,55.29,0.54,0.34,10.24,-15.82,2.35,2.93,0
1,2016-06-30 12:00:00 AM,2553.207333,-60.91,183663.25,317093.17,65.57,0.50,0.29,9.70,-17.67,-51.47,3.22,1
2,2016-03-31 12:00:00 AM,2179.086667,-1944.68,183285.52,336350.55,-840.35,0.52,0.28,9.99,-14.43,-21.33,3.07,2
3,2015-12-30 12:00:00 AM,2136.294889,-1944.68,183285.52,336350.55,-38.14,0.41,0.22,9.86,-14.43,-21.33,3.88,3
4,2015-09-30 12:00:00 AM,2442.015000,1684.07,185458.96,352887.46,46.17,0.42,0.22,8.69,-9.44,-21.33,3.71,4
5,2015-06-30 12:00:00 AM,2972.705222,2196.62,186231.10,373318.93,30.33,0.54,0.28,8.51,0.84,-1.68,2.90,5
6,2015-03-31 12:00:00 AM,3280.935333,4784.91,193620.78,379926.48,23.48,0.60,0.30,9.36,9.67,41.89,2.61,6
7,2014-12-30 12:00:00 AM,3716.189556,4784.91,193620.78,379926.48,25.90,0.66,0.33,9.84,9.67,41.89,2.30,7
8,2014-09-30 12:00:00 AM,3783.974889,6192.96,193553.48,372521.77,23.88,0.78,0.41,10.49,11.10,-1.88,1.93,8
9,2014-06-30 12:00:00 AM,3566.488111,6237.21,196520.35,352182.92,26.35,0.74,0.39,10.94,11.28,19.72,2.05,9
10,2014-03-31 12:00:00 AM,3695.938444,7462.78,196397.76,342951.01,18.66,0.73,0.41,10.11,-3.98,-35.53,2.02,10
11,2013-12-30 12:00:00 AM,3898.787556,7462.78,196397.76,342951.01,20.19,0.79,0.44,10.60,-3.98,-35.53,1.87,11
12,2013-09-30 12:00:00 AM,3835.451667,8741.67,194934.88,346912.05,17.08,0.80,0.43,9.96,-6.70,-29.96,1.89,12
13,2013-06-28 12:00:00 AM,3899.112222,11777.21,188591.53,368367.54,13.74,0.77,0.39,8.64,-19.92,-34.77,2.04,13
14,2013-03-29 12:00:00 AM,4138.780889,14059.21,187668.69,394935.64,11.07,0.84,0.39,7.57,-6.76,-22.67,2.26,14
15,2012-12-28 12:00:00 AM,4199.688000,14059.21,187668.69,394935.64,11.79,0.89,0.42,7.87,-6.76,-22.67,2.12,15
16,2012-09-28 12:00:00 AM,4359.383667,11515.21,185473.90,406663.38,15.24,0.94,0.43,10.08,-3.58,-27.48,2.03,16
17,2012-06-29 12:00:00 AM,4492.997778,17374.77,191636.48,411907.24,10.94,0.90,0.41,8.38,14.93,-48.78,2.14,17
18,2012-03-30 12:00:00 AM,4670.924000,15574.06,188243.29,120413.03,11.41,0.98,0.72,19.16,17.52,-68.52,2.01,18
19,2011-12-29 12:00:00 AM,4527.738889,15574.06,188243.29,120413.03,11.26,0.97,0.76,20.16,17.52,-68.52,2.04,19
20,2011-09-30 12:00:00 AM,5056.846778,18846.97,188784.11,117557.61,9.10,0.94,0.72,13.95,29.63,73.03,2.09,20
21,2011-06-30 12:00:00 AM,5462.445000,19894.41,176855.52,233957.53,11.78,1.19,0.78,19.06,24.52,-56.57,1.69,21
22,2011-03-31 12:00:00 AM,5577.904444,42509.31,316329.30,284795.05,9.98,1.40,1.04,6.60,26.84,14.71,1.24,22
23,2010-12-30 12:00:00 AM,5687.523222,42509.31,316329.30,284795.05,9.69,1.36,1.01,6.43,26.84,14.71,1.27,23
24,2010-09-30 12:00:00 AM,5716.101778,43825.34,308490.44,271359.68,9.40,1.43,1.52,5.93,27.37,1060.61,1.29,24
25,2010-06-30 12:00:00 AM,5894.918333,28174.63,314773.52,261113.48,9.84,1.31,1.43,5.82,-11.59,12.82,1.46,25
26,2010-03-31 12:00:00 AM,6554.878778,22470.60,300231.68,270430.86,19.25,1.60,1.60,9.66,-21.73,-49.05,1.61,26
27,2009-12-30 12:00:00 AM,6112.503778,22470.60,300231.68,270430.86,22.08,1.84,1.83,11.06,-21.73,-49.05,1.40,27
28,2009-09-30 12:00:00 AM,5289.027667,22599.07,288728.72,288894.49,17.34,1.51,1.36,8.38,-15.19,-91.09,1.77,28
29,2009-06-30 12:00:00 AM,4489.809000,39159.72,284374.03,296339.38,10.57,1.35,1.14,5.99,51.09,59.69,2.04,29
30,2009-03-31 12:00:00 AM,4138.551444,39729.14,280948.84,269156.22,7.41,1.18,1.09,4.20,66.82,85.99,2.36,30
31,2008-12-30 12:00:00 AM,4365.397111,39729.14,280948.84,269156.22,7.70,1.22,1.14,4.37,66.82,85.99,2.27,31
32,2008-09-30 12:00:00 AM,5805.879889,37066.71,273314.07,235118.76,9.60,1.46,1.51,5.38,29.09,52.75,1.95,32
33,2008-06-30 12:00:00 AM,5990.986444,33617.71,255382.06,214978.52,12.89,1.92,2.01,7.09,1.71,-19.56,1.58,33
34,2008-03-31 12:00:00 AM,6151.397444,35683.84,248602.53,214086.54,10.81,1.74,1.80,6.17,-0.05,0.83,1.47,34
35,2007-12-28 12:00:00 AM,6985.881556,35683.84,248602.53,214086.54,13.04,2.10,2.17,7.46,-0.05,0.83,1.22,35
36,2007-09-28 12:00:00 AM,5923.744333,35805.17,239977.45,214111.65,15.16,2.53,2.53,8.76,23.39,32.69,1.05,36
37,2007-06-29 12:00:00 AM,4701.185667,29206.70,222699.61,193783.40,11.17,1.78,1.76,6.31,3.85,2.37,1.59,37
38,2007-03-30 12:00:00 AM,3823.247889,24061.33,210699.95,191842.35,13.21,1.66,1.66,6.98,-2.70,-18.35,1.84,38
39,2006-12-28 12:00:00 AM,3091.333222,24061.33,210699.95,191842.35,10.42,1.31,1.31,5.49,-2.70,-18.35,2.33,39
40,2006-09-29 12:00:00 AM,2764.483222,25637.78,203364.27,193573.43,7.81,1.08,1.03,4.25,-12.56,-45.75,2.92,40
41,2006-06-30 12:00:00 AM,2874.449222,36862.78,195134.51,210441.04,6.72,1.12,1.03,3.68,-7.07,-33.29,2.83,41

In [124]:
# WIN_LOSS 구하기.

for i in range(len(df_copy)-1, 0, -1):
    if df_copy['MA'][i-1] > df_copy['MA'][i]:
        df_copy['W/L'].iloc[i] = '1'
    else:
        df_copy['W/L'].iloc[i] = '0'

C:\Users\ASUS\Anaconda3\lib\site-packages\pandas\core\indexing.py:205: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_with_indexer(indexer, value)

In [125]:
df_copy

,Date,MA,EPS,SPS,PER,PBR,PSR,EV/EBITDA,매출액growth,영업이익growth,FYO growth,BPS,W/L
0,2016-09-30 12:00:00 AM,2588.862444,1898.81,200485.11,311158.40,55.29,0.54,0.34,10.24,-15.82,2.35,2.93,0
1,2016-06-30 12:00:00 AM,2553.207333,-60.91,183663.25,317093.17,65.57,0.50,0.29,9.70,-17.67,-51.47,3.22,1
2,2016-03-31 12:00:00 AM,2179.086667,-1944.68,183285.52,336350.55,-840.35,0.52,0.28,9.99,-14.43,-21.33,3.07,1
3,2015-12-30 12:00:00 AM,2136.294889,-1944.68,183285.52,336350.55,-38.14,0.41,0.22,9.86,-14.43,-21.33,3.88,1
4,2015-09-30 12:00:00 AM,2442.015000,1684.07,185458.96,352887.46,46.17,0.42,0.22,8.69,-9.44,-21.33,3.71,0
5,2015-06-30 12:00:00 AM,2972.705222,2196.62,186231.10,373318.93,30.33,0.54,0.28,8.51,0.84,-1.68,2.90,0
6,2015-03-31 12:00:00 AM,3280.935333,4784.91,193620.78,379926.48,23.48,0.60,0.30,9.36,9.67,41.89,2.61,0
7,2014-12-30 12:00:00 AM,3716.189556,4784.91,193620.78,379926.48,25.90,0.66,0.33,9.84,9.67,41.89,2.30,0
8,2014-09-30 12:00:00 AM,3783.974889,6192.96,193553.48,372521.77,23.88,0.78,0.41,10.49,11.10,-1.88,1.93,0
9,2014-06-30 12:00:00 AM,3566.488111,6237.21,196520.35,352182.92,26.35,0.74,0.39,10.94,11.28,19.72,2.05,1
10,2014-03-31 12:00:00 AM,3695.938444,7462.78,196397.76,342951.01,18.66,0.73,0.41,10.11,-3.98,-35.53,2.02,0
11,2013-12-30 12:00:00 AM,3898.787556,7462.78,196397.76,342951.01,20.19,0.79,0.44,10.60,-3.98,-35.53,1.87,0
12,2013-09-30 12:00:00 AM,3835.451667,8741.67,194934.88,346912.05,17.08,0.80,0.43,9.96,-6.70,-29.96,1.89,1
13,2013-06-28 12:00:00 AM,3899.112222,11777.21,188591.53,368367.54,13.74,0.77,0.39,8.64,-19.92,-34.77,2.04,0
14,2013-03-29 12:00:00 AM,4138.780889,14059.21,187668.69,394935.64,11.07,0.84,0.39,7.57,-6.76,-22.67,2.26,0
15,2012-12-28 12:00:00 AM,4199.688000,14059.21,187668.69,394935.64,11.79,0.89,0.42,7.87,-6.76,-22.67,2.12,0
16,2012-09-28 12:00:00 AM,4359.383667,11515.21,185473.90,406663.38,15.24,0.94,0.43,10.08,-3.58,-27.48,2.03,0
17,2012-06-29 12:00:00 AM,4492.997778,17374.77,191636.48,411907.24,10.94,0.90,0.41,8.38,14.93,-48.78,2.14,0
18,2012-03-30 12:00:00 AM,4670.924000,15574.06,188243.29,120413.03,11.41,0.98,0.72,19.16,17.52,-68.52,2.01,0
19,2011-12-29 12:00:00 AM,4527.738889,15574.06,188243.29,120413.03,11.26,0.97,0.76,20.16,17.52,-68.52,2.04,1
20,2011-09-30 12:00:00 AM,5056.846778,18846.97,188784.11,117557.61,9.10,0.94,0.72,13.95,29.63,73.03,2.09,0
21,2011-06-30 12:00:00 AM,5462.445000,19894.41,176855.52,233957.53,11.78,1.19,0.78,19.06,24.52,-56.57,1.69,0
22,2011-03-31 12:00:00 AM,5577.904444,42509.31,316329.30,284795.05,9.98,1.40,1.04,6.60,26.84,14.71,1.24,0
23,2010-12-30 12:00:00 AM,5687.523222,42509.31,316329.30,284795.05,9.69,1.36,1.01,6.43,26.84,14.71,1.27,0
24,2010-09-30 12:00:00 AM,5716.101778,43825.34,308490.44,271359.68,9.40,1.43,1.52,5.93,27.37,1060.61,1.29,0
25,2010-06-30 12:00:00 AM,5894.918333,28174.63,314773.52,261113.48,9.84,1.31,1.43,5.82,-11.59,12.82,1.46,0
26,2010-03-31 12:00:00 AM,6554.878778,22470.60,300231.68,270430.86,19.25,1.60,1.60,9.66,-21.73,-49.05,1.61,0
27,2009-12-30 12:00:00 AM,6112.503778,22470.60,300231.68,270430.86,22.08,1.84,1.83,11.06,-21.73,-49.05,1.40,1
28,2009-09-30 12:00:00 AM,5289.027667,22599.07,288728.72,288894.49,17.34,1.51,1.36,8.38,-15.19,-91.09,1.77,1
29,2009-06-30 12:00:00 AM,4489.809000,39159.72,284374.03,296339.38,10.57,1.35,1.14,5.99,51.09,59.69,2.04,1
30,2009-03-31 12:00:00 AM,4138.551444,39729.14,280948.84,269156.22,7.41,1.18,1.09,4.20,66.82,85.99,2.36,1
31,2008-12-30 12:00:00 AM,4365.397111,39729.14,280948.84,269156.22,7.70,1.22,1.14,4.37,66.82,85.99,2.27,0
32,2008-09-30 12:00:00 AM,5805.879889,37066.71,273314.07,235118.76,9.60,1.46,1.51,5.38,29.09,52.75,1.95,0
33,2008-06-30 12:00:00 AM,5990.986444,33617.71,255382.06,214978.52,12.89,1.92,2.01,7.09,1.71,-19.56,1.58,0
34,2008-03-31 12:00:00 AM,6151.397444,35683.84,248602.53,214086.54,10.81,1.74,1.80,6.17,-0.05,0.83,1.47,0
35,2007-12-28 12:00:00 AM,6985.881556,35683.84,248602.53,214086.54,13.04,2.10,2.17,7.46,-0.05,0.83,1.22,0
36,2007-09-28 12:00:00 AM,5923.744333,35805.17,239977.45,214111.65,15.16,2.53,2.53,8.76,23.39,32.69,1.05,1
37,2007-06-29 12:00:00 AM,4701.185667,29206.70,222699.61,193783.40,11.17,1.78,1.76,6.31,3.85,2.37,1.59,1
38,2007-03-30 12:00:00 AM,3823.247889,24061.33,210699.95,191842.35,13.21,1.66,1.66,6.98,-2.70,-18.35,1.84,1
39,2006-12-28 12:00:00 AM,3091.333222,24061.33,210699.95,191842.35,10.42,1.31,1.31,5.49,-2.70,-18.35,2.33,1
40,2006-09-29 12:00:00 AM,2764.483222,25637.78,203364.27,193573.43,7.81,1.08,1.03,4.25,-12.56,-45.75,2.92,1
41,2006-06-30 12:00:00 AM,2874.449222,36862.78,195134.51,210441.04,6.72,1.12,1.03,3.68,-7.07,-33.29,2.83,0

In [24]:
df_fin = df_copy.iloc[1:len(df_copy),:]

In [25]:
df_fin.to_csv("80.csv")